version: '3'

services:
    nginx:
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - "./:/var/www/symfony"

    php:
        volumes:
            - "./:/var/www/symfony"
        working_dir: "/var/www/symfony"
