version: '3'

services:
    nginx:
        build:
            context: docker/nginx
            dockerfile: test.Dockerfile
        container_name: nginx_test

    php:
        build:
            context: docker/php
            dockerfile: test.Dockerfile
        container_name: php_test
